export const PORTUGUESE_UNIVERSITIES = [
  'Universidade de Aveiro',
  'Universidade dos Açores',
  'Universidade do Algarve',
  'Universidade de Coimbra',
  'Universidade de Évora',
  'Universidade de Lisboa',
  'Universidade da Madeira',
  'Universidade do Minho',
  'Universidade Nova de Lisboa',
  'Universidade do Porto',
  'Universidade de Trás-os-Montes e Alto Douro',
  'Universidade da Beira Interior',
  'ISCTE - Instituto Universitário de Lisboa',
  'Instituto Politécnico de Bragança',
  'Instituto Politécnico de Castelo Branco',
  'Instituto Politécnico de Coimbra',
  'Instituto Politécnico da Guarda',
  'Instituto Politécnico de Leiria',
  'Instituto Politécnico de Lisboa',
  'Instituto Politécnico de Portalegre',
  'Instituto Politécnico do Porto',
  'Instituto Politécnico de Santarém',
  'Instituto Politécnico de Setúbal',
  'Instituto Politécnico de Tomar',
  'Instituto Politécnico de Viana do Castelo',
  'Instituto Politécnico de Viseu',
  'Instituto Politécnico do Cávado e do Ave',
  'Universidade Católica Portuguesa',
  'Universidade Autónoma de Lisboa',
  'Universidade Lusíada',
  'Universidade Lusófona',
  'Instituto Superior Técnico',
].sort();

export const PORTUGUESE_CITIES = [
  'Aveiro',
  'Beja',
  'Braga',
  'Bragança',
  'Castelo Branco',
  'Coimbra',
  'Évora',
  'Faro',
  'Funchal',
  'Guarda',
  'Leiria',
  'Lisboa',
  'Ponta Delgada',
  'Portalegre',
  'Porto',
  'Santarém',
  'Setúbal',
  'Viana do Castelo',
  'Vila Real',
  'Viseu',
].sort();
